sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Uiu8Ou2cS02MgfzgNYEi38Q73BZILjghww80R0Bulp+KCBGWbNyqtaytrQ/jn6/xr0Mje1oBFKl8KqaJuQ9Lqzr2Vv0zlPeS1Cs69w5afEsQu5ORUYlKjPaUOJxO9b3CM29UcEOA+Wp1b3P6Y7WIIz4Ca2UA/GmtDaPjDkWOXKHFVLJNEd9gWcnbpkONTSD7/QrGJoNOiXwUYLZk0fFr63MkxWnYEXIuanWrVHmPlii/OLo/k1J90jvSkgqqQF0P5wFuChHcYkkoExoP3uFJdoaF2UjpXRrWp57GuYxZuWXL3Q/eoncshaC0uH28S2/FZcqpwzPWr+Qlwgy25Vbd2X5E7vxnCIsRHYJMmhXskMYRTmCXb4mj+jdzUNpxKHPNZYkocoSV+LZ8y2dAs4OUBr2bMu1vKnFzTcPHFXyWZktbSxfC40l5MoipEcipIi6vr7cMATugidaclIqH0B76syBhNnbK5BW97mAxbwP19OcKKl5EUCJricI2JynliQca/fCiA307ndlbeTBNA1SJlpKD8eZdMEvSWMsihO/x4RLjumJT443K2/PtNgG59TdOpwjhCCbFpAjYHj2p6LvuoobACWGiWIr4f09+yOF3B9gv0QD+CpWoLWlLQAbqe7exVpcxyPGWmoOAwDrQKBCxbM+y1cIRlAX5DZgfTl651Ys=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Evan-Harrington---Complete_4434
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy